### ISSUE TITLE
When you create your Azure Application for some reason it is not creating an SPN (enterprise app)

### ISSUE THREAD

**Issue by oppknox** [Matthewsre/terraform-azurerm-microservices#28]
![image](https://user-images.githubusercontent.com/34199047/105272735-cd9b0f00-5b4e-11eb-8f79-e20024700839.png)

**Comment by Matthewsre** [comment]
Thanks for working through this with me. Fixed the missing permissions that were causing the AAD auth to fail and have everything working without the service principal. Fixes are released in v0.1.26
