### ISSUE TITLE
When calling from an SPN Role checking will fail

### ISSUE THREAD

**Issue by oppknox** [Matthewsre/terraform-azurerm-microservices#96]
`az ad signed-in-user show --query objectId `is a user command, if running while in the context of an SPN you'll receive the error below. The simple fix is to instead use this command `az account show --query user.name 
`
```
az : ERROR: ResourceNotFoundError: Resource not found for the segment 'me'.
At line:1 char:1
+ az ad signed-in-user show
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (ERROR: Resource...e segment 'me'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Comment by Matthewsre** [comment]
To prevent this issue, you need to use pass in "-objectId "<objectId>" when not running under the context of a user and using the initialization powershell script

**Comment by oppknox** [comment]
I just found you on this thread, looks like you are well aware :)

https://github.com/Azure/azure-cli/issues/10439

**Comment by oppknox** [comment]
this bugged me... this CLI command will return the actual object id of an SPN if you know the client id 
az ad sp show --id cef09388-fb98-4b01-81a5-fc8808947468
